### ISSUE TITLE
main() eror!!!

### ISSUE THREAD

**Issue by kuratkull** [Gregory-Eales/crypto-pump#1]
..

**Comment by Gregory-Eales** [comment]
Hey, the code isn't finalized yet, just a small side project for fun. The terminal io might be kind of strange on different systems. I was using terminal on macOS Big Sir while writing this. Try removing the color and loading effects and see if it works.

**Comment by kuratkull** [comment]
It's a nice project and has been running smoothly so far. We will follow up further. I wish you continued success. good luck 

can it be sold manually?

**Comment by Gregory-Eales** [comment]
Yes, you could put an input condition that will halt the program until input is given. If you want live prices shown on the terminal you would probably need some sort of threading/multiprocessing.

**Comment by kuratkull** [comment]
how can we fix errors. the problem still continues

`
@space_it
def check_sell_status(client, ticker, orderID):
	s = get_sell_status(client, ticker, orderID)
	txt = "[{}] percent filled: {}%".format(get_time(), s)
	sys.stdout.write(txt)

	while s < 100:
		s = get_buy_status(client, ticker, orderID)
		s = next(gen)
		txt = "\r"+"[{}] percent filled: {}%".format(get_time(), s)
		sys.stdout.write(txt)
`

**get_buy_status** and **get_sell_status** Undefined variable 'get_sell_status'pylint(undefined-variable)

**Comment by kuratkull** [comment]
@Gregory-Eales (https://user-images.githubusercontent.com/81049823/112763498-5893fc00-900d-11eb-838e-69af0f4dda13.png)

binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL

An error occurs during the purchase order. why could it be.

**Comment by kuratkull** [comment]
`	          order =  client.order_market_buy(
			symbol=ticker+"BTC",
			quantity=qty
			)`

"quantity=100" it gets 100 when I do. here he should get the full balance. I am getting a qty = qty error.
